### ISSUE TITLE
bluetoothmanager not rescan BLEDevices?

### ISSUE THREAD

**Issue by subhash08** [SmartCodeUnited/SmartBluetooth-ios-objective-c#12]
When first time viewcontroller is load , its working fine, but when we come again on viewcontroller its not scan again , even after calling `  [self.bluetoothDeviceManager startScanningWithType:SCUBluetoothDeviceManagerBluetoothTypeBLE];` 
help needed

**Comment by Lewanny** [comment]
Thank you for your question issue , we fixed the problem in the latest version , you can try it again .

**Comment by subhash08** [comment]
thank you issue solve, now I,m closing this issue.

**Comment by ifeegoo** [comment]
OK,thank you for your support! @subhash08
